apiVersion: v1
kind: Namespace
metadata:
  name: playground
---
apiVersion: v1
kind: Pod
metadata:
  namespace: playground
  name: go-playground
  labels:
    app: go-playground
spec:
  containers:
  - name: go-playground
    image: golang:1.23-alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    workingDir: /app
